## Table of Contents
1. Introduction
2. Objectives
3. Data
4. Methodology
 * Analyze District 1
 * K-mean Cluster District 1
 * Analyze District 3
 * K-mean Cluster District 3
5. Results
6. Discussion
7. Conclusion

# 1.Introduction
Ho Chi Minh City, formerly known as Saigon, once “The Pearl of the Far East” is the second largest city in Vietnam (the largest being Hanoi). It is the most crowded city in the country with the official population of over 8 million people on the total area of over 2,095 km2. The city now comprises 19 districts and 5 suburban districts. District 1, along the Saigon River, where downtown Saigon is located, is the commercial center and contains most of the city’s monuments and landmarks. 8 km away in district 5 resides a big market or Cho Lon where Chinese community lives. With favorable weather the whole year round and the convenient access from other countries by air, by road and by sea, Ho Chi Minh city is a busy and dynamic metropolitan.

###### * Brief information about both cities:*

District 1 (Vietnamese: Quận 1) is the central urban district of Ho Chi Minh City, the largest city in Vietnam. With a total area of 7.7211 km2 (2.9811 sq mi) the district has a population of 204,899 people as of 2010.The district is divided into 10 small subsets which are called wards (phường). District 1 contains most of the city's administrative offices, consulates, and large buildings. District 1 is the busiest district in the city with the highest living standards. Đồng Khởi street and Nguyễn Huệ boulevard in District 1 are the city's two main commercial centers. Đồng Khởi street is an area in high demand for real estate, hitting a record price of USD50,000 per square meter in 2007. (source: https://en.wikipedia.org/wiki/District_1,_Ho_Chi_Minh_City)

District 3 (Vietnamese: Quận 3) is an urban district of Ho Chi Minh City, the largest city in Vietnam. Together with District 1, District 3 is considered the bustling heart of the city, with several businesses, religious sites, historical buildings and tourist attractions. (source: https://en.wikipedia.org/wiki/District_3,_Ho_Chi_Minh_City)


# 2.Objective
In this project, I will study in details the area classification using Foursquare data and machine learning segmentation and clustering. The aim of this project is to segment areas of District 1 and District 3 based on the most common places captured from Foursquare.

I will determine the similarity or dissimilarirty of both district and classification residential/tourism places/others of area located inside District 1 and District 3 by using segmentation and clustering


# 3. Data
Using the data get from common government website and then translate into English and restructure to csv file for easier manipulation and reading. I uploaded that file to my github for references. Link to the files are:

https://github.com/vhhlinh/Study_data/blob/master/HCMC_District.csv

Another aspect to consider for this project is the Foursquare data. I believe that the data as good as provided, meaning although we are using Foursquare data for segmentation and clustering, the amount and accuracy of data captured can't 100% determine correct classification in real world.

###  Reference of data

In [1]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_d2a62246b7af47aba928b58d3432c339 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='9WdJzzV3kakYC_zt1XQbZp_6DP8nB22nzvE8bZWygqKs',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_d2a62246b7af47aba928b58d3432c339.get_object(Bucket='coursera9linhvu-donotdelete-pr-spdjuxzcebc3vp',Key='HCMC_District.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

HCMC = pd.read_csv(body)
HCMC.head(5)

   No.  District code District name              Ward_name  Ward code
0    1            760    District 1          Tan Dinh Ward      26734
1    2            760    District 1            Da Kao Ward      26737
2    3            760    District 1          Ben Nghe Ward      26740
3    4            760    District 1         Ben Thanh Ward      26743
4    5            760    District 1  Nguyen Thai Binh Ward      26746

In [3]:
Dist1 = HCMC[HCMC['District name'] == 'District 1']
Dist3 = HCMC[HCMC['District name'] == 'District 3']

In [4]:
# examine data to find number of District 1
print('District 1 has {} wards.'.format(
        len(Dist1),
        Dist1.shape[0]
    )
)
Dist1.head(15)

District 1 has 10 wards.

   No.  District code District name              Ward_name  Ward code
0    1            760    District 1          Tan Dinh Ward      26734
1    2            760    District 1            Da Kao Ward      26737
2    3            760    District 1          Ben Nghe Ward      26740
3    4            760    District 1         Ben Thanh Ward      26743
4    5            760    District 1  Nguyen Thai Binh Ward      26746
5    6            760    District 1      Pham Ngu Lao Ward      26749
6    7            760    District 1      Cau Ong Lanh Ward      26752
7    8            760    District 1          Co Giang Ward      26755
8    9            760    District 1   Nguyen Cu Trinh Ward      26758
9   10            760    District 1           Cau Kho Ward      26761

In [5]:
# examine data to find number of District 3
print('District 3 has {} wards.'.format(
        len(Dist3),
        Dist3.shape[0]
    )
)
Dist3.head(15)

District 3 has 14 wards.

     No.  District code District name Ward_name  Ward code
134  135            770    District 3    Ward 8      27121
135  136            770    District 3    Ward 7      27124
136  137            770    District 3   Ward 14      27127
137  138            770    District 3   Ward 12      27130
138  139            770    District 3   Ward 11      27133
139  140            770    District 3   Ward 13      27136
140  141            770    District 3    Ward 6      27139
141  142            770    District 3    Ward 9      27142
142  143            770    District 3   Ward 10      27145
143  144            770    District 3    Ward 4      27148
144  145            770    District 3    Ward 5      27151
145  146            770    District 3    Ward 3      27154
146  147            770    District 3    Ward 2      27157
147  148            770    District 3    Ward 1      27160

In [6]:
import numpy as np 
import time
import pandas as pd

import json # library to handle JSON files
import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe


!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

!conda install -c conda-forge folium=0.5.0 --yes 
import folium # map rendering library
import folium # map rendering library
from folium import plugins

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

import seaborn as sns

# import k-means from clustering stage
from sklearn.cluster import KMeans

print('Libraries imported.')

Solving environment: done

# All requested packages already installed.

Solving environment: done

# All requested packages already installed.

Libraries imported.

In [7]:
# using Geocoder to get the Latitude and Longitude of District 1
i = 1
for i in range (1,11):
    address = (Dist1['Ward_name'].head(i).values)[i-1] + ' District 1, Ho Chi Minh City'
    geolocator = Nominatim(user_agent="my-application")
    location = geolocator.geocode(address)
    latitude = location.latitude
    longitude = location.longitude
    print (Dist1['Ward_name'].head(i).values[i-1], latitude, longitude)

Tan Dinh Ward 10.7932029 106.6902032
Da Kao Ward 10.7884755 106.698318
Ben Nghe Ward 10.7812343 106.7026503
Ben Thanh Ward 10.7728665 106.6943
Nguyen Thai Binh Ward 10.7688283 106.6987969
Pham Ngu Lao Ward 10.7667074 106.6920012
Cau Ong Lanh Ward 10.7654593 106.696587971109
Co Giang Ward 10.7620099 106.6933648
Nguyen Cu Trinh Ward 10.76239705 106.686651362325
Cau Kho Ward 10.75752515 106.688900225853

In [8]:
# using Geocoder to get the Latitude and Longitude of District 3
i = 1
for i in range (1,15):
    address = (Dist3['Ward_name'].head(i).values)[i-1] + ' District 3, Ho Chi Minh City'
    geolocator = Nominatim(user_agent="my-application")
    location = geolocator.geocode(address)
    latitude = location.latitude
    longitude = location.longitude
    print (Dist3['Ward_name'].head(i).values[i-1], latitude, longitude)

Ward 8 10.7979139 106.6748516
Ward 7 10.7806202 106.6863996
Ward 14 10.7895656 106.6786342
Ward 12 10.7882328 106.673673806804
Ward 11 10.7929518 106.6749979
Ward 13 10.7863145 106.6778478
Ward 6 10.779185 106.6911478
Ward 9 10.7816101 106.680207279703
Ward 10 10.7814723 106.6760941
Ward 4 10.7737617 106.6832254
Ward 5 10.7904337 106.6623708999
Ward 3 10.7701933 106.6790566
Ward 2 10.7973984 106.6876578
Ward 1 10.7988373 106.6826542